class ErrorCode:
    # Auth
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_TOKEN = "INVALID_TOKEN"

    # Product
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"

    # Payment
    PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
    PAYMENT_ALREADY_COMPLETED = "PAYMENT_ALREADY_COMPLETED"
